# POST http://localhost:3000/store/users
# content-type: application/json

# {
#   "email": "piresj@mcmaster.ca"
# }




# PUT http://localhost:3000/store/users/U-001
# content-type: application/json

# {
#   "firstName": "Josh",
#   "lastName": "Pires"
# }





# # 
# POST http://localhost:3000/store/users/U-000/cart
# content-type: application/json

# {
#   "itemId": "I-003",
#   "quantity": 2
# }




# # 
# PUT http://localhost:3000/store/users/U-000/cart/I-003
# content-type: application/json

# {
#   "quantity": 0
# }




# # 
# DELETE http://localhost:3000/store/users/U-000/cart/I-003




# GET http://localhost:3000/store/users/U-000/cart


